language: node_js

node_js:
    - "node"

install:
    - npm install -g typescript@next
    - npm install -g mocha
    - npm install -g typings
    - typings install
    - npm install

before_script:
    - cd $TRAVIS_BUILD_DIR

script:
    - npm run build
    - npm run test
